$ErrorActionPreference = "Stop"

function New-HexSecret {
  param([int] $Bytes = 32)

  $buffer = New-Object byte[] $Bytes
  $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $generator.GetBytes($buffer)
  }
  finally {
    $generator.Dispose()
  }
  return ([BitConverter]::ToString($buffer) -replace "-", "").ToLowerInvariant()
}

function Read-PlainSecret {
  param(
    [Parameter(Mandatory = $true)]
    [string] $Prompt
  )

  $secure = Read-Host $Prompt -AsSecureString
  $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
  }
  finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
  }
}

$mistralApiKey = Read-PlainSecret "Cle API Mistral (saisie masquee)"
$resendApiKey = Read-PlainSecret "Cle API Resend re_... (saisie masquee)"

if ($mistralApiKey.Length -lt 12) {
  throw "La cle Mistral semble trop courte."
}

if (-not $resendApiKey.StartsWith("re_") -or $resendApiKey.Length -lt 8) {
  throw "La cle Resend doit commencer par re_."
}

$postgresPassword = New-HexSecret 32
$sessionSecret = New-HexSecret 48
$identityOutboxSecret = New-HexSecret 48
$mfaSecret = New-HexSecret 48
$documentSecret = New-HexSecret 48
$backupSecret = New-HexSecret 48

$environment = @"
LYDOC_COMPOSE_PROJECT_NAME=lydoc
LYDOC_API_ENV_FILE=.env
LYDOC_DEPLOYMENT_PROFILE=free-beta
LYDOC_BIND_ADDRESS=127.0.0.1
LYDOC_WEB_PORT=3000
LYDOC_API_PORT=3001
LYDOC_POSTGRES_VOLUME=lydoc-production-postgres
LYDOC_DOCUMENT_VOLUME=lydoc-production-documents
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=postgresql://lydoc:$postgresPassword@postgres:5432/lydoc
APP_URL=https://lydoc.fr
API_URL=https://api.lydoc.fr
NEXT_PUBLIC_APP_URL=https://lydoc.fr
NEXT_PUBLIC_API_URL=https://api.lydoc.fr
SECURITY_CONTACT_EMAIL=contact@lydoc.fr
PORT=3001
TRUST_PROXY=true
TRUST_PROXY_CIDRS=10.0.1.6/32
API_GENERAL_RATE_LIMIT_PER_MINUTE=120
SESSION_SECRET=$sessionSecret
IDENTITY_OUTBOX_ENCRYPTION_SECRET=$identityOutboxSecret
MFA_ENCRYPTION_SECRET=$mfaSecret
MFA_ENCRYPTION_KEY_ID=admin-mfa-2026-09
MFA_ENCRYPTION_PREVIOUS_KEYS={}
ADMIN_SESSION_TTL_MINUTES=30
AUTH_SCRYPT_CONCURRENCY=2
AUTH_SCRYPT_QUEUE_LIMIT=8
AUTH_EMAIL_DAILY_GLOBAL_LIMIT=500
AUTH_REGISTER_HOURLY_GLOBAL_LIMIT=100
AUTH_RESEND_HOURLY_GLOBAL_LIMIT=100
AUTH_FORGOT_HOURLY_GLOBAL_LIMIT=100
AUTH_MFA_CHALLENGE_HOURLY_GLOBAL_LIMIT=200
AUTH_REGISTER_HOURLY_IDENTIFIER_LIMIT=10
AUTH_RESEND_HOURLY_IDENTIFIER_LIMIT=5
AUTH_FORGOT_HOURLY_IDENTIFIER_LIMIT=5
AUTH_MFA_CHALLENGE_HOURLY_IDENTIFIER_LIMIT=5
AUTH_DISPATCH_MIN_RESPONSE_MS=250
AUTH_PENDING_USER_TTL_HOURS=48
AUTH_CLEANUP_INTERVAL_MINUTES=60
AUTH_EXPOSE_TEST_TOKENS=false
IDENTITY_EMAIL_OUTBOX_INTERVAL_MS=1000
IDENTITY_EMAIL_OUTBOX_CONCURRENCY=2
IDENTITY_EMAIL_OUTBOX_BATCH_SIZE=10
IDENTITY_EMAIL_OUTBOX_LEASE_SECONDS=120
IDENTITY_EMAIL_OUTBOX_MAX_ATTEMPTS=6
DOCUMENT_ENCRYPTION_SECRET=$documentSecret
DOCUMENT_ENCRYPTION_KEY_ID=primary-2026-09
DOCUMENT_ENCRYPTION_PREVIOUS_KEYS={}
BACKUP_ENCRYPTION_SECRET=$backupSecret
BACKUP_ENCRYPTION_KEY_ID=backups-2026-09
BACKUP_ENCRYPTION_PREVIOUS_KEYS={}
MISTRAL_API_KEY=$mistralApiKey
MANAGED_POSTAL_ENABLED=false
NEXT_PUBLIC_MANAGED_POSTAL_ENABLED=false
NEXT_PUBLIC_DOCUMENTS_PAGE_ENABLED=false
POSTAL_PROVIDER=mock
SERVICE_POSTAL_ENV=sandbox
SERVICE_POSTAL_DEFAULT_PRODUCT=vertesuivi
SERVICE_POSTAL_PRODUCTION_ENABLED=false
SERVICE_POSTAL_API_KEY=
SERVICE_POSTAL_WEBHOOK_SECRET=
SERVICE_POSTAL_WEBHOOK_TOLERANCE_SECONDS=300
SERVICE_POSTAL_ALLOW_LEGACY_WEBHOOK_TOKEN=false
SERVICE_POSTAL_REQUEST_TIMEOUT_MS=10000
SERVICE_POSTAL_REQUEST_MAX_ATTEMPTS=2
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NOTIFICATIONS_REQUIRED=false
RESEND_API_KEY=$resendApiKey
RESEND_FROM_EMAIL=Lydoc <notifications@mail.lydoc.fr>
CONTACT_TO_EMAIL=contact@lydoc.fr
CONTACT_DAILY_LIMIT=200
CONTACT_DAILY_EMAIL_LIMIT=3
CONTACT_DAILY_CLIENT_LIMIT=20
CONTACT_HOURLY_ATTEMPT_LIMIT=400
CONTACT_HOURLY_EMAIL_ATTEMPT_LIMIT=10
CONTACT_HOURLY_CLIENT_ATTEMPT_LIMIT=40
AI_DAILY_ACCOUNT_CALL_LIMIT=10
MISTRAL_DAILY_CALL_LIMIT=1000
MISTRAL_MAX_CONCURRENT_REQUESTS=2
DOCUMENT_PENDING_UPLOAD_GLOBAL_BYTES=524288000
DOCUMENT_UPLOAD_CONCURRENCY_GLOBAL=4
DOCUMENT_UPLOAD_CONCURRENCY_ACCOUNT=2
STORAGE_WRITE_RESERVATION_TTL_SECONDS=900
DOCUMENT_STORAGE_MIN_FREE_BYTES=1073741824
DOCUMENT_STORAGE_GLOBAL_BYTES=107374182400
DOCUMENT_RETENTION_DAYS=365
SENSITIVE_DOCUMENT_RETENTION_DAYS=30
DOCUMENT_DELETION_GRACE_DAYS=7
DOCUMENT_MIGRATION_BACKUP_DAYS=7
DOCUMENT_RETENTION_AUTOMATION_ENABLED=true
DOCUMENT_RETENTION_INTERVAL_MINUTES=360
ACCOUNT_ERASURE_PURGE_GRACE_DAYS=7
ACCOUNT_LEGAL_RECORD_RETENTION_DAYS=3650
LOG_HTTP=true
"@

Set-Clipboard -Value $environment.Trim()
Write-Host "Le bloc Coolify a ete copie dans le presse-papiers." -ForegroundColor Green
Write-Host "Collez-le uniquement dans Production, puis cliquez sur Save." -ForegroundColor Cyan
